"""added new column

Revision ID: 6409bccae98a
Revises: 62ee279eb9b5
Create Date: 2024-07-18 18:27:01.209071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6409bccae98a'
down_revision = '62ee279eb9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_username', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('to_username', sa.String(length=128), nullable=False))
        batch_op.drop_constraint('transfer_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('transfer_username_key', ['username'])
        batch_op.drop_column('to_username')
        batch_op.drop_column('from_username')

    # ### end Alembic commands ###
